package models

import "time"

// ─── Request Models ────────────────────────────────────────────────────────
// These structs represent what the client sends in the request body.
// Validation tags are read by the validator package in the service layer.

// CreateUserRequest is the expected request body for POST /users.
// The client provides name and dob — id is auto-generated by the database.
type CreateUserRequest struct {
	Name string `json:"name" validate:"required,min=2,max=100"`
	Dob  string `json:"dob"  validate:"required,datetime=2006-01-02"`
}

// UpdateUserRequest is the expected request body for PUT /users/:id.
// Same fields as create — id comes from the URL parameter, not the body.
type UpdateUserRequest struct {
	Name string `json:"name" validate:"required,min=2,max=100"`
	Dob  string `json:"dob"  validate:"required,datetime=2006-01-02"`
}

// ─── Response Models ───────────────────────────────────────────────────────
// These structs represent what the API returns to the client.
// Age is calculated dynamically — it is never stored in the database.

// UserResponse is the shape of a single user in API responses.
type UserResponse struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Dob  string `json:"dob"`
	Age  int    `json:"age"`
}

// ─── Pagination Models ─────────────────────────────────────────────────────
// These structs handle paginated list responses and query parameters.

// PaginationQuery holds the query parameters for paginated endpoints.
// Example: GET /users?page=2&page_size=10
type PaginationQuery struct {
	Page     int `query:"page"`
	PageSize int `query:"page_size"`
}

// PaginatedResponse wraps a list of users with pagination metadata.
// This gives clients everything they need to build a pagination UI.
type PaginatedResponse struct {
	Data       []UserResponse `json:"data"`
	Total      int64          `json:"total"`
	Page       int            `json:"page"`
	PageSize   int            `json:"page_size"`
	TotalPages int            `json:"total_pages"`
}

// ─── Error Models ──────────────────────────────────────────────────────────

// ErrorResponse is the standard shape for all error responses.
// Using a consistent error shape means clients always know
// where to find the error message.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ─── Helpers ───────────────────────────────────────────────────────────────

// FormatDob formats a time.Time into a YYYY-MM-DD string
// for consistent date representation in API responses.
func FormatDob(t time.Time) string {
	return t.Format("2006-01-02")
}
